language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t danparsons/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danparsons/docker-react npm run test